version: '3.8'
services:
  # Main application service
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8008:8000"
    env_file:
      - ./app/.env.dev
    depends_on:
      - app-db
  # Database service https://hub.docker.com/_/postgres
  app-db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env.dev

volumes:
  postgres_data:
